# version: '3'

 services:
   db:
     image: mongo:5
     restart: always
     ports:
       - 27017:27017
     environment:
         MONGODB_DATABASE: ${MONGONAME}
     volumes:
      - ./mongo:/data/db

#La version antigua la deje en la parte superior